### ISSUE TITLE
refactor: use SimpleGit.checkIsRepo() instead of shell commands

### ISSUE THREAD

**Issue by nicolas377** [gpsystem/create-geofs-plugin#67]
Right now, we use `isInGitRepo()` to check if a git repository already exists. [`isInGitRepo()`](https://github.com/gpsystem/create-geofs-plugin/blob/main/src/git/isInGitRepo.ts) runs shell commands, but simple-git offers a function for that. [SimpleGit.checkIsRepo()](https://github.com/steveukx/git-js/blob/main/simple-git/src/lib/tasks/check-is-repo.ts) essentially does the exact same thing we do, except it takes the burden off of us to run shell commands.

**Comment by nicolas377** [comment]
We'll just have to run SimpleGit.checkIsRepo() after we initialize the `git` constant here.
https://github.com/gpsystem/create-geofs-plugin/blob/f433007af58a368b8e492328ac727ebc0097a924/src/git/index.ts#L15

**Comment by RishiKumarRay** [comment]
const git = simpleGit(destination);
SimpleGit.checkIsRepo()  
so we need to add this at line 16? and this will check if repository exists? or we need to make some more changes?

**Comment by Guy-Adler** [comment]
If I understood @nicolas377 correctly, what we need to do is to first check whether git is installed (lines 10-12), and then check if we are in a repo. If we are, we can just return from the function (just like in line 12).

**Comment by nicolas377** [comment]
I'll be opening PRs for this and #64 later today or tomorrow. I marked #49 as good first issue because reducing code complexity is a very broad topic that I need more participation on. That also expanded to this issue and #64.
