### ISSUE TITLE
global variables are undefined to eslint

### ISSUE THREAD

**Issue by Guy-Adler** [gpsystem/create-geofs-plugin#94]
Eslint considers global variables of the GeoFS API undefined because they are not defined under `globals` on `.eslintrc.yml`.

**Comment by nicolas377** [comment]
This is a bit of a sticky situation, since the geofs api will continue to evolve, with potentially more globals. That would mean we have to constantly change eslint configs for js templates. (no-undef is turned off for ts templates, since ts does that job already)

For right now, 489f7221867d7ce626b5abf0db8e08635931f86f is a good solution, but I'm reopening this to solicit further discussion about a potentially better fix.

**Comment by Guy-Adler** [comment]
The problem is that it is impossible (as far as I know) to declare globals to eslint in any way other than to directly specify them, and the other option is to disable the rule altogether, which is more problematic in my opinion. I think currently the best solution will be a GitHub action of sorts that will automatically update the globals list based on the globals declared on `index.d.ts` in @geps/geofs-types. Since we will only need to update it whenever the version of @geps/geofs-types is updated, will it be possible to link that action with the dependabot PR?

**Comment by nicolas377** [comment]
My first idea is to maybe write a script that will extract the globals from @geps/geofs-types, and we can run that manually on dependabot prs for @geps/geofs-types. That script would be really hard to write though.

**Comment by Guy-Adler** [comment]
Actually, it might be quite easy: typeDoc, which we use for the documentation, can output it as JSON. since we're exporting all global types (and one other interface, which we can ignore in the script), it will all be included on the JSON. In theory, shouldn't we be able to just pick the keys from the JSON object and insert them into the YAML?

**Comment by Guy-Adler** [comment]
after running `npx typedoc --entryPointStrategy expand typings --json types.json`, a file named `types.json` is created. in that JSON, we can get all definitions by going to `children` (an array) and then looping over it until getting to an object with `"name": "globals"`. From it, we can get to the defined globals. something like this should do the trick:
```typescript
declare const json: any; // assume the json is already loaded.
const globals: string[] = [];

json.children.find(el => el.name === "globals").forEach(el => el.children.forEach(g => globals.push(g.name)));
```

Then, we will just have to append the list to the yaml.

**Comment by nicolas377** [comment]
We can manually update the eslint config where needed.
